//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauHoi()
        {
            this.CTKetQuas = new HashSet<CTKetQua>();
        }
    
        public int id { get; set; }
        public Nullable<int> MaDeThi { get; set; }
        public string DapAn { get; set; }
        public string Cau_hoi { get; set; }
        public string Dap_an_1 { get; set; }
        public string Dap_an_2 { get; set; }
        public string Dap_an_3 { get; set; }
        public string Dap_an_4 { get; set; }
        public string Ghi_chu { get; set; }
        public Nullable<int> Muc_do_kho { get; set; }
    
        public virtual DeThi DeThi { get; set; }
        public virtual DoKho DoKho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTKetQua> CTKetQuas { get; set; }
    }
}
