//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKetQua
    {
        public int MaThanhVien { get; set; }
        public int MaCauHoi { get; set; }
        public Nullable<bool> DaTl { get; set; }
        public string KQ { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
